#+TITLE: Zappa

* Settings
:REFERENCES:
- https://github.com/Miserlou/Zappa#advanced-settings
:END:

** exclude
Default excludes:
#+BEGIN_SRC python
  ZIP_EXCLUDES = [
      '*.exe', '*.DS_Store', '*.Python', '*.git', '.git/*', '*.zip', '*.tar.gz',
      '*.hg', '*.egg-info', 'pip', 'docutils*', 'setuputils*', '__pycache__/*'
  ]
#+END_SRC

This feature is implemented with [[https://docs.python.org/2/library/shutil.html#shutil.ignore_patterns][shutil.ignore_patterns]].
This only checks the name, not the fullpath.
So if you want to exclude ~__pycache__/*~, you have to specify it like ~__pycache__~.
There is no way to exclude relative paths to the project currently.

Actually, even ~ZIP_EXCLUDES~ has improper patterns!

:REFERENCES:
- https://github.com/Miserlou/Zappa/blob/cf8d09f7f286048e66c1f4da505876e2ea19c903/zappa/core.py#L197
- https://github.com/Miserlou/Zappa/issues/692
:END:

* Topics
** Packaging by Zappa
It seems that Zappa packages all files in the current working directory.
So, it doesn't need to ~pip install .~ to include the project code.

:REFERENCES:
- https://github.com/Miserlou/Zappa/blob/cf8d09f7f286048e66c1f4da505876e2ea19c903/zappa/core.py#L507
:END:

** slim_handler
#+BEGIN_QUOTE
When the slim handler is called on a cold start,
it downloads the large project zip from S3 and unzips it in Lambda’s shared ~/tmp~ space.
All subsequent calls to that warm Lambda share the ~/tmp~ space and have access to the project files;
so it is possible for the file to only download once if the Lambda stays warm.
#+END_QUOTE

:REFERENCES:
- https://github.com/Miserlou/zappa-blog/blob/master/posts/slim-handler.md
:END:

* How-to
** Configure HTTPS using AWS Certificate Manager
Because CloudFront requires ACM in ~us-east-1~, Zappa is also under this restriction.
So, make sure to use the proper region when registering ACM.

#+BEGIN_SRC json
    "dev": {
      "certificate_arn": "arn:aws:acm:us-east-1:1234:certificate/abcd",
      "domain": "dev.galpi.io",
    }
#+END_SRC

I'm not sure whether it is safe to publish aws arn in a public git repository.

#+BEGIN_SRC shell
  $ zappa certify
#+END_SRC

:REFERENCES:
- https://github.com/Miserlou/Zappa#ssl-certification
:END:
