#+TITLE: webpack

* Table of Contents :TOC_3_gh:
- [[#concepts][Concepts]]
- [[#entry][Entry]]
- [[#loaders][Loaders]]
  - [[#css-loader][css-loader]]
  - [[#style-loader][style-loader]]
  - [[#babel-loader][babel-loader]]
- [[#plugins][Plugins]]
- [[#cli][CLI]]
- [[#configuration][Configuration]]
  - [[#mode][mode]]
- [[#development][Development]]
- [[#production][Production]]

* Concepts
- https://webpack.js.org/concepts/

#+BEGIN_SRC javascript
  const HtmlWebpackPlugin = require('html-webpack-plugin'); //installed via npm
  const webpack = require('webpack'); //to access built-in plugins
  const path = require('path');

  const config = {
    entry: './path/to/my/entry/file.js',
    output: {
      path: path.resolve(__dirname, 'dist'),
      filename: 'my-first-webpack.bundle.js'
    },
    module: {
      rules: [
        { test: /\.txt$/, use: 'raw-loader' }
      ]
    },
    plugins: [
      new webpack.optimize.UglifyJsPlugin(),
      new HtmlWebpackPlugin({template: './src/index.html'})
    ]
  };

  module.exports = config;
#+END_SRC

- ~entry~ indicates which module webpack should use to begin building out its internal dependency graph.
- ~output~ tells webpack where to emit the bundles it creates and how to name these files.
- ~module~ (loaders) is used to more than just JavaScript files
- ~plugins~ can be leveraged to perform a wider range of tasks.

* Entry
#+BEGIN_SRC javascript
  const config = {
    entry: {
      app: './src/app.js',
      vendors: './src/vendors.js'
    }
  };
#+END_SRC

#+BEGIN_SRC javascript
  const config = {
    entry: {
      pageOne: './src/pageOne/index.js',
      pageTwo: './src/pageTwo/index.js',
      pageThree: './src/pageThree/index.js'
    }
  };
#+END_SRC

* Loaders
- https://webpack.js.org/concepts/loaders/
- https://webpack.js.org/loaders/
- https://webpack.js.org/configuration/module/#module-rules

Loaders can be chained by passing multiple loaders,
which will be applied from *right to left* (last to first configured).

** css-loader
- https://github.com/webpack-contrib/css-loader

The ~css-loader~ interprets ~@import~ and ~url()~ like ~import/require()~ and will resolve them.
Actually do nothing with it.

** style-loader
- https://github.com/webpack-contrib/style-loader
- https://stackoverflow.com/questions/34039826/webpack-style-loader-vs-css-loader
- Adds CSS to the DOM by injecting a ~<style>~ tag

** babel-loader
- https://github.com/babel/babel-loader

- Note the version compatibility

#+BEGIN_SRC shell
  # webpack 3.x | babel-loader 8.x | babel 7.x
  npm install babel-loader@8.0.0-beta.0 @babel/core @babel/preset-env webpack

  # webpack 3.x babel-loader 7.x | babel 6.x
  npm install babel-loader babel-core babel-preset-env webpack
#+END_SRC

* Plugins
- https://webpack.js.org/concepts/plugins/

#+BEGIN_SRC javascript
  function ConsoleLogOnBuildWebpackPlugin() {

  };

  ConsoleLogOnBuildWebpackPlugin.prototype.apply = function(compiler) {
    compiler.plugin('run', function(compiler, callback) {
      console.log("The webpack build process is starting!!!");

      callback();
    });
  };
#+END_SRC

* CLI
- https://webpack.js.org/api/cli/

#+BEGIN_SRC shell
  webpack [--config webpack.config.js]
#+END_SRC

* Configuration
- https://webpack.js.org/configuration/

** mode
- https://medium.com/webpack/webpack-4-mode-and-optimization-5423a6bc597a
- https://medium.com/webpack/webpack-4-released-today-6cdb994702d4

webpack 4 now ships with two sets of defaults. ~development~ and ~production~.
These are the two values to which mode can be set to.

#+BEGIN_SRC shell
  webpack --mode production
#+END_SRC

* Development
- https://webpack.js.org/guides/development/

#+BEGIN_SRC json
      "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1",
  +     "watch": "webpack --watch",
        "build": "webpack"
      },
#+END_SRC

Or,

#+BEGIN_SRC json
      "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1",
        "watch": "webpack --watch",
  +     "start": "webpack-dev-server --open",
        "build": "webpack"
      },
#+END_SRC

* Production
- https://medium.com/@rajaraodv/webpack-the-confusing-parts-58712f8fcad9
