#+TITLE: Design of Computer Programs

* About this Course
This is my study note of the free course named [[https://www.udacity.com/course/design-of-computer-programs--cs212][Design of Computer Programs]] from Udacity.

This course teaches how to approach programming problems and
how to fight against the complexity of programs,
which are the most important skills for a programmer to possess.

The professor, [[http://norvig.com/][Peter Norvig]], teaches these skills through a pose-try-feedback loop.

The lessons consists of small programming problems.
He makes us solve them first, and then shows his own solution as feedback.
Most of the time, I was surprised by his elegant solutions.

This is one of my favorite computer courses of all time.

* Lessons
- [[lesson1.org][Lesson 1]]: Poker
- [[lesson2.org][Lesson 2]]: Zebra Puzzle, Cryptarithmetic
- [[lesson3.org][Lesson 3]]: Regex, Parser
- [[lesson4.org][Lesson 4]]: Water Pouring, Bridge, Missionaries and Cannibals
- [[lesson5.org][Lesson 5]]: Porcine Probability
- [[lesson6.org][Lesson 6]]: Word Games
- [[lesson7.org][Lesson 7]]: Practice Exam
