#+TITLE: Datadog

* How-to
** Config minimally
#+BEGIN_EXAMPLE
  [Main]
  dd_url: https://app.datadoghq.com
  api_key: <api-key>
  hostname: nightly00-all-000-k
  tags:
    - role:couchbase
    - cluster:yeonghoey
#+END_EXAMPLE

# For one-liner tags:
#+BEGIN_SRC yaml
  tags: ["role:couchbase", "cluster:yeonghoey"]
#+END_SRC

* Reference
** Setup
#+BEGIN_SRC shell
  DD_API_KEY=<your-api-key> bash -c "$(curl -L https://raw.githubusercontent.com/DataDog/dd-agent/master/packaging/datadog-agent/source/install_agent.sh)"

  # Just install without DD_API_KEY
  DD_API_KEY=x DD_INSTALL_ONLY=true bash -c "$(curl -L https://raw.githubusercontent.com/DataDog/dd-agent/master/packaging/datadog-agent/source/install_agent.sh)"
#+END_SRC

:REFERENCES:
- https://docs.datadoghq.com/guides/basic_agent_usage/ubuntu/
:END:

** Management
#+BEGIN_SRC shell
  sudo /etc/init.d/datadog-agent start
  sudo /etc/init.d/datadog-agent stop
  sudo /etc/init.d/datadog-agent restart
  sudo /etc/init.d/datadog-agent status
  sudo /etc/init.d/datadog-agent info
  sudo /etc/init.d/datadog-agent info -v
  sudo /etc/init.d/datadog-agent check [integration]
  sudo /etc/init.d/datadog-agent check [integration] check_rate
#+END_SRC

#+BEGIN_SRC shell
  # Configs
  /etc/dd-agent/datadog.conf  # Agent
  /etc/dd-agent/conf.d/       # Integrations

  # Logs
  /var/log/datadog/supervisord.log (since 3.8.0)
  /var/log/datadog/collector.log
  /var/log/datadog/dogstatsd.log
  /var/log/datadog/forwarder.log
#+END_SRC

** Host Naming
- Datadog uniquely identify hosts by ~hostname~
- Host name cadidates (order of priority)
  1. ~agent-hostname~: If a host name is explicitly set in the Agent configuration file.
  2. ~hostname~: If the DNS host name is not an EC2 default (e.g. ip-192-0-0-1).
  3. ~instance-id~: If the Agent can reach the EC2 metadata endpoint from the host.
  4. ~hostname~: Fall back on the DNS host name even if it is an EC2 default.
- By documentation, with default configuration, my instance should have ~hostname~, but always I got ~instance-id~.

#+BEGIN_EXAMPLE
  ec2-hostname: ip-10-42-134-4.ap-northeast-1.compute.internal
  local-ipv4: 10.42.134.4
  socket-hostname: yeonghoey-cb-001
  hostname: i-0ccfeb8b6dc2ce863
  local-hostname: ip-10-42-134-4.ap-northeast-1.compute.internal
  instance-id: i-0ccfeb8b6dc2ce863
  socket-fqdn: localhost
#+END_EXAMPLE

- They say there is ~alias~ for other names, but it seems useless. Every graph features shows ~hostname~ only.
- So, just always put ~hostname~ in ~/etc/dd-agent/datadog.conf~

#+BEGIN_EXAMPLE
  hostname: mymachine.mydomain
#+END_EXAMPLE

:REFERENCES:
- https://docs.datadoghq.com/hostnames/
:END:

** Tags
- Tags can be both only ~name~ values or ~key:value~ pairs.
- Tags under ~integrations~ only takes effect integrations dashboard

#+BEGIN_EXAMPLE
  tags:
    - firsttag
    - secondtag
    - thirdtagregion:east
#+END_EXAMPLE

#+BEGIN_EXAMPLE
  tags:
    - region:nw
    - application:database
    - database:primary
    - role:sobotka
#+END_EXAMPLE

:REFERENCES:
- https://docs.datadoghq.com/guides/tagging/
:END:

** Metrics
:REFERENCES:
- https://docs.datadoghq.com/integrations/system/
:END:

* Topics
