#+TITLE: Hugo

* Overview
* Reference
** Front Matter
:REFERENCES:
- https://gohugo.io/content-management/front-matter/#front-matter-variables
:END:

** Shortcodes
:REFERENCES:
- https://gohugo.io/content-management/shortcodes/
:END:

** Templating
*** Syntax
Hugo uses Go’s ~html/template~ and ~text/template~ libraries as the basis for the templating.

~{{ . }}~ stands for the context variable.
~{{ $. }}~ stands for the global context variable.

#+BEGIN_SRC go
  // Front matter
  {{ .Title }}      // built-in
  {{ .Params.foo }} // user defined

  // Site configuration
  {{ .Site.bar }}
#+END_SRC

#+BEGIN_SRC go
  // Methods and Fields are Accessed via dot Notation
  {{ .Params.bar }}


  //Parentheses Can be Used to Group Items Together
  {{ if or (isset .Params "alt") (isset .Params "caption") }} Caption {{ end }}


  // Variables
  {{ $address := "123 Main St."}}
  {{ $address }}


  // Includes
  {{ template "partials/header.html" . }}
  {{ partial "header.html" . }}


  // Range
  {{ range array }}
      {{ . }}
  {{ end }}

  {{range $element := array}}
      {{ $element }}
  {{ end }}

  {{range $index, $element := array}}
     {{ $index }}
     {{ $element }}
  {{ end }}


  // Conditionals
  {{ if isset .Params "alt" }}
      {{ index .Params "alt" }}
  {{else}}
      {{ index .Params "caption" }}
  {{ end }}


  // With (changes the context '{{ . }}')
  {{ with .Params.title }}<h4>{{ . }}</h4>{{ end }}
#+END_SRC

:REFERENCES:
- https://gohugo.io/templates/lookup-order/
:END:

*** Functions
:REFERENCES:
- https://gohugo.io/functions
:END:

*** Variables
:REFERENCES:
- https://gohugo.io/variables
:END:

* Terminology
* Topics
** Directory Structure
#+BEGIN_EXAMPLE
  .
  ├── archetypes
  ├── config.toml
  ├── content
  ├── data
  ├── layouts
  ├── static
  │   ├─ css
  │   ├─ js
  │   └─ img
  └── themes
#+END_EXAMPLE

- ~archetypes~  :: Templetes for new content files
- ~config.toml~ :: [[https://gohugo.io/getting-started/configuration/#all-variables-toml][All Variables, TOML]]
- ~content~     :: Each top-level folder in Hugo is considered a [[https://gohugo.io/content-management/sections/][content section]].
- ~data~        :: Configuration files
- ~layouts~     :: Templetes in the form of ~.html~
- ~static~      :: Static content like images, CSS, Javascript, etc.

** Themes
#+BEGIN_EXAMPLE
  /themes/<THEME>/static/js/jquery.min.js
#+END_EXAMPLE

When you want to customize the file above which is provided by the theme, you can override it with:

#+BEGIN_EXAMPLE
  /static/js/jquery.min.js
#+END_EXAMPLE

** Path
:REFERENCES:
- https://gohugo.io/content-management/organization/#path-breakdown-in-hugo
:END:

** Taxonomies
#+BEGIN_EXAMPLE
  Actor                    <- Taxonomy
      Bruce Willis         <- Term
          The Sixth Sense  <- Value
          Unbreakable      <- Value
          Moonrise Kingdom <- Value
      Samuel L. Jackson    <- Term
          Unbreakable      <- Value
          The Avengers     <- Value
          xXx              <- Value
#+END_EXAMPLE

Define taxonomies in ~config.toml~ as ~singular_key = "plural_value"~ form:
#+BEGIN_SRC toml
  [taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"
#+END_SRC

Add taxonomies to content with front matter:
#+BEGIN_SRC toml
  +++
  title = "Hugo: A fast and flexible static site generator"
  tags = [ "Development", "Go", "fast", "Blogging" ]
  categories = [ "Development" ]
  series = [ "Go Web Dev" ]
  slug = "hugo"
  project_url = "https://github.com/gohugoio/hugo"
  +++
#+END_SRC

:REFERENCES:
- https://gohugo.io/content-management/taxonomies/
:END:

* How-to
* Links
