#+TITLE: Docker

* Table of Contents :TOC_1_gh:
- [[#overview][Overview]]
- [[#reference][Reference]]
- [[#terminology][Terminology]]
- [[#topics][Topics]]
- [[#how-to][How-to]]
- [[#links][Links]]
- [[#staging][Staging]]

* Overview
* Reference
** Dockerfile
*** RUN
- https://docs.docker.com/engine/reference/builder/#run

- ~RUN <command>~
  - shell form, the command is run in a shell, which by default is /bin/sh -c on Linux or cmd /S /C on Windows)
  - You can use a ~\~ (backslash) to continue a single ~RUN~ instruction onto the next line.

- ~RUN ["executable", "param1", "param2"]~
  - This, exec form, makes it possible to avoid shell string munging,
    and to ~RUN~ commands using a base image that does not contain the specified shell executable.

*** CMD
- https://docs.docker.com/engine/reference/builder/#cmd
- ~CMD ["executable","param1","param2"]~ (exec form, this is the preferred form)
- ~CMD ["param1","param2"]~ (as default parameters to ENTRYPOINT)
- ~CMD command param1 param2~ (shell form)
- The main purpose of a CMD is to provide defaults for an executing container

* Terminology
* Topics
* How-to
** Install docker with a single command
- https://get.docker.com/

#+BEGIN_SRC shell
  curl -sSL https://get.docker.com/ | sh
#+END_SRC

** Install docker on Amazon Linux instance
- http://docs.aws.amazon.com/AmazonECS/latest/developerguide/docker-basics.html#install_docker

#+BEGIN_SRC shell
  sudo yum update -y
  sudo yum install -y docker
  sudo service docker start
  sudo usermod -a -G docker ec2-user
#+END_SRC

** Access internet from containers when private DNS intrudes
- https://github.com/moby/moby/issues/13381#issuecomment-159836002
- https://github.com/docker/docker/issues/9889

In private network with private DNS, the network administrator often blocks access to common DNS like ~8.8.8.8~.
This may cause to block access to internet within the docker container.

In this case, the private DNS is used within docker containers with ~--dns~ option.
To use this option by default, put the following line in ~/etc/default/docker~:
#+BEGIN_SRC shell
  # Use DOCKER_OPTS to modify the daemon startup options.
  DOCKER_OPTS="--dns 10.10.0.1 --dns 10.10.0.2"
#+END_SRC

Additionally, ~systemd~ script for ~docker~ doesn't read ~/etc/default/docker~ and ~$DOCKER_OPTS~.
To fix it, add following lines to ~/lib/systemd/system/docker.service~:
#+BEGIN_EXAMPLE
  [Service]
  // ...
  EnvironmentFile=-/etc/default/docker
  ExecStart=/usr/bin/dockerd -H fd:// $DOCKER_OPTS
#+END_EXAMPLE

* Links
- [[https://github.com/wsargent/docker-cheat-sheet#table-of-contents][docker-cheat-sheet]]

* Staging
