#+TITLE: Personal Statement
#+AUTHOR: Yeongho Kim

#+OPTIONS: author:t date:nil

#+LATEX_HEADER: \usepackage[margin=1.0in]{geometry}

#+LATEX_HEADER: \usepackage{titling}
#+LATEX_HEADER: \setlength{\droptitle}{-14ex}

#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER:\setlength{\parindent}{2ex}

#+LATEX_HEADER: \pagenumbering{gobble}
#+LATEX: \vspace{-6ex}

About a year ago, I developed an AI with Deep Q Learning for a simple dodging game I made.
It was for my 2-week personal project for the new comers of my current team.
The personal project was a kind of a welcome task for new comers.
The only restriction of the project was that the outcome had to be a game.
When I got to do my one, I had been fascinated by Deep Q Learning introduced by Atari paper.
Even though I had no background of machine learning and 2 weeks seemed not enough, I decided to push myself to pursue it.
I went over the Atari paper several times. I analyzed the example codes on GitHub. I crammed basics of neural networks on the Internet.
After all, I managed to finish the project. The performance of the AI was not so good, but at least it seemed to work.
I fused the AI to the game as a partner of the player.
In the game, the player and the AI should control a spaceship in tandem.
The game was not so fun, but it was enough to inspire my teammates. 

As the previous story, my greatest strength is that I can find my curiosity in anything and make it real.
Thanks to the point, even though my work experience has been very broad, I've been successful throughout my career. 

I developed an intelligent matchmaking system for Bubble Fighter.
Bubble Fighter is a water gun fight online game for kids.
At the time I joined the team, the game had already been servicing for 5 years.
It had no matchmaking system.
Like many other modern online games, my team wanted a matchmaking system to hook players more.
I researched TrueSkill to develop intelligent matchmaking system for the game.
TrueSkill is a player rating system which is based on Bayesian inference.
It is a kind of an advanced version of the popular Elo rating system.
Apart from its complex nature, I thought it was almost impossible for me, as a junior developer who just graduated from university, to develop the whole system.
But my curiosity made me achieve it.
I wanted to understand the complex mathematical symbols and graphs on the papers about TrueSkill.
I taught myself the mathematical backgrounds for understanding the algorithm via Khan Academy and many other YouTube lectures.
I read lots of other implementation codes and wrote lots of prototypes.
Through this, I could implement the algorithm and system gradually.
I also wrote lots of tests to prove that the implementation works correctly.
Over 6 months of striving for the matchmaking system, The matchmaking system named Arena was successfully launched.

FROGRAMS which is servicing WATCHA and WATCHA PLAY is a one of famous startups in Korea for their machine learned movie recommendation service.
Their recommendation engine was implemented in Scala, a JVM based functional programming language.
Because I also had curiosity about functional programming, I joined the team for the experience of both Data Science and functional programming.
I really enjoyed programming in Scala.
I took Scala Coursera courses and watched lots of Scala conferences on YouTube.
I read the famous Functional Programming in Scala book and solved all the practice problems of the book.
I was new to the language when I joined the team, I soon became the most proficient Scala programmer on the team.
