* Personal Statement Draft1
One of my lifetime goals is to make an influential indie game based on data science, including machine learning.

Since I was 11, when I was fascinated by games, my life is deeply connected to games.
My parents supported me to pursue it, and I could learn Turbo Pascal and Turbo C when I was kid.


I was fascinated by games since I was 7. Since then, I'd been dreaming of becoming a game developer.

I told my dream to my parents. They supported me to pursue my dream. 

I could attend a computer academies to learn computer algorithms.
After 1-2 years of learning them, when I was a middle school student, 
I even participated regional preliminaries of International Olympiad in Informatics.

But I didn't get any noticeable result, because I was not so interested in them.
The middle school student of me couldn't related computer science and game development.
It was another boring math problem at that moment.

I quit to continue my effort to algorithms at high school.
I shifted my goal as becoming a game designer.


like being more fluent in English, joining the bleeding edge, bU.S is setting the pace of my profession thesedays.

I think my forte is to find my curiosity in any task. 
Following my curiosity, I've been teaching myself and being successful during my career.

When I was a junior developer, I got to implement the matchmaking system for Bubble Fighter.
I had to research TrueSkill, a player rating algorithm, based on Bayesian statistical inference.
Apart from its complex nature, it was almost impossible for a junior developer to understand, design and implement the whole system.

But my curiosity led me to read over all the related papers.
It made me lookup all the mathematical symbols I was not familiar with on those papers.
I got to lots of 
to try lots of examples of the algorithm.



I've read lots CS books, taking lots of courses from Coursera and Udacity.


The broad range of successful achievements in my career proves the point.

* Personal Statement Draft2
About a year ago, I made a simple dodging game and implemented Deep Q Learning to play it.
It was my 2 week personal project of free subject for the new comers of my current team.
Implementing Deep Q Learning for 2 weeks without any background was challenging.
I was afraid of failing to finish the project, but I didn't care about it. 
I was just fascinated with it because it has been a dream of mine to build an intelligent game AI.
Anyway, after 2 weeks, I managed to finish my project. My implementation was not so great, but at least it seemed to work.

AI is the perfect field for mine, as a curisotiy and my field.
I majored both Philosophy and Computer science. The 

I majored Philosophy. I wanted to become a game designer.
I though Philosophy would be helpful to design virtual worlds, values of virtual characters, etc.
But

철학과에서 절 매료시켰던 것은 물질과 마음의 철학이라는 과목이었습니다.
지능이란 무엇인지, 우리의 뇌와 마음에 대한 과거 철학자들의 통찰을 이해하기도 하고,
관련 주제를 다룬 SF 소설들을 읽고 함께 토론하는 시간도 갖고 했었는데, 이 과목이 무쳑 흥미로웠습니다.

한편, 철학과를 다니면서 여가 시간에는 게임을 직접 만들어보고 싶다는 생각에 독학으로 C++, TCP/IP 프로그래밍을 공부해서 다양한 자작 게임들을 만들었습니다.
이 때 게임을 만드는 행위 자체에 매료되면서 게임 디자인보다는 게임 개발로 방향을 옮기기 시작했었습니다. 그리고 컴퓨터 공학을 이중 전공으로 선택하게 되었습니다.

컴퓨터 공학 수업에서 놀랐던 점은 철학과 수업과 컴퓨터 공학이 무척 닮아 있다는 점이었습니다.
철학과에서 재미있게 들었던 기호논리학 수업은 이산수학 수업과 정말 밀접하게 비슷한 내용을 다루고 있었습니다.
컴퓨터 공학 수업에서 제일 좋아했던 AI 수업들은, 물질과 마음의 철학 수업의 심화 과정이라고 느껴질 만큼, 그 학문적 뿌리를 공유하고 있었습니다.

졸업 후 한국에서 제일 유명한 게임 회사 중 하나인 넥슨에 입사했습니다. 저는 버블파이터라는 게임을 개발했는데요,
제 흥미를 잘 어필해서 베이지안 확률 추론을 응용한 TrueSkill 알고리즘을 기반으로 한 매치메이킹 시스템을 디자인하고 구현했습니다.
TrueSkill은 자체적으로도 무척 복잡한 알고리즘인데다, 이것을 서비스 중인 온라인 게임에 녹여내는 것은 무척 도전적인 일이었지만,
매치메이킹 시스템을 성공적으로 런칭할 수 있었습니다.

Data Science와 머신러닝에 더 갈증을 느낀 저는 머신러닝을 기반으로 영화를 추천해주는 Watcha를 서비스하는 Frograms로 직장을 이동했습니다.
당시 저는 머신러닝 외에도 함수형 프로그래밍에 무척 흥미를 갖고 있었는데요,
후로그램스에는 대학원에서 머신러닝을 전공한 데이터 사이언티스트들이 많이 있었고,
덕분에 저는 머신러닝보다는 함수형 언어인 Scala를 활용한 프로그래밍의 전반적인 가이드란일 세우고 코드베이스의 전체적인 품질 향상시키는 일을 맡게 되었습니다.

이후 온라인 오픈월드 게임인 듀랑고를 개발하는 현재 팀인 왓스튜디오에서 일하게 되었습니다.
야생과 오픈월드라는 게임 배경 자체가 흥미로웠고, 데이터 과학을 적용할 여지 역시 더 풍부할 것이라고 기대했습니다.

저는 대부분의 경험이 독학을 통해서 이루어졌기 때문에, Data Science에 있어서 체계적인 학습 경험이 부족하다고 느껴왔습니다.
제다가 후로그람스에서처럼, 계속해서 현재 잘하는 일을 맡게 되다 보면, Data Science로 커리어를 이동해나가는 것이 쉽지 않을 것이라고도 생각해왔구요.
또한, 저는 첨단 기술을 달리는 미국에서 커리어를 이어나가보고 싶다는 꿈도 있습니다.

MCS-DS 코스는 제가 당면한 부족한 접을 잘 채워 줄 수 있으리라는 확신을 얻었습니다.
제 목표를 이루는 도움닫기 과정이 될 것이라 확신합니다.

* Personal Statement Draft3
# 제 인생의 목표 중 하나는 데이터 과학과 인공지능을 통해 영향력있는 인디게임을 만드는 것입니다.
# 저는 재미 뿐만아니라 가치관과 세상을 보는 시각을 바꿔주는 인디게임들을 가치 있게 생각합니다.
# 그리고 저는 데이터 과하고가 AI가, 저 자신 뿐만아니라 게임을 플레이하는 플레이어들을 매료시키고
# 세상을 보는 새로운 관점을 줄 수 있다고 믿습니다.

# 인디게임은 그렇다치고, 왜 데이터과학과 인공지능인가 하면, 제가 철학과 컴퓨터를 공부하면서 느꼈던 학문적 뿌리의 공통점에
# 매료되었기 때문이라고 할 수 있습니다. 철학 수업인 기호논리학과 컴퓨터 수업인 이산수학이 정말 비슷함을 느꼈을 때,
# 인지와 지성 등에 대해 고민하는 철학 수업과, 인공지능 수업의 학문적 뿌리가 같다는 걸 느꼈 때,
# 뭔가 데이터과학과 인공지능이 제 천직처럼 느껴지기도 했습니다. 게임을 좋아하는 제가, 데이터과학과 인공지능을 통해
# 독특하고 사람들에게 영감을 주는 게임을 만든다면, 이것은 저 밖에 만들어 낼 수 없는 가치일 거라 생각합니다.

제 가장 큰 장점은 어떤 일이든 간에 제가 느낄 수 있는 흥미를 찾아내고, 거기에 몰입할 수 있다는 점 입니다.
이 강점은 제가 다양한 일을 스스로 빠르게 학습할 수 있게 해주었습니다.

2주의 제한된 기간동안의 자유 주제 개인 프로젝트로 배경지식이 전무한 상태에서 Deep Q Learning을 구현하기도 했습니다.

현재 있는 팀에서 서비스를 확장해나감에 따라 Cloud Computing의 자동화가 필요한 시점이 되자, 저는 금방 Terraform의 전문가가 되었고

팀에 DevOps가 필



# 1년 전 쯤에, 간단한 총알 피하기 게임을 만들고, 이것을 Deep Q Learning으로 구현한 적이 있습니다.
# 지금 다니는 스튜디오의 신규 입사자들을 위한 자유 주제 프로젝트로 2주 동안했던 것이었습니다.
# 2주만에 배경 지식없이 Deep Q Learning을 구현하는 것은 꽤나 도전적이었습니다.
# 하지만 저는 Tensor Flow와 Deep Q Learning에 매료되었고, 프로젝트를 완료하지 못할지도 모른다는 걱정도 있었지만,
# 밀어붙였습니다. Deep Q Learning을 소개하는 Atari 페이퍼를 읽고 또 읽으며, 계속 새롭게 실험해보고 하면서, 겨우 완성시킬 수 있었습니다.
# 썩 훌륭하진 않았지만, 어느 정도 동작하는 것 같은 모습이 무척 흥미로웠습니다.

이 후에 팀에서 처음 맡은 일은 데이터 파이프라인을 구축하는 일이었습니다.
게임 속에서 일어나는 다양한 이벤트 데이터들을 스트리밍하고 이를 분석할 수 있도록 하는 시스템을 처음부터 끝까지 설계하고 구현했습니다.
현재 듀랑고는 정식 오픈 전인 CBT 중인데, 하루에도 수백기가 이상의 데이터가 스트리밍되고, Parquet로 배치작업이 동작합니다.
덕분에 팀의 게임 디자이너들이 Zeppelin을 통해 분석해보고 다양한 인사이트를 얻을 수 있는 환경을 제공할 수 있었습니다.

하지만 이후에는 데이터과학과 연관된 경험을 많이 쌓을 수는 없었습니다. 저는 새로운 걸 도전하고 스스로 배우는 것을 즐기지만
포지션 자체가 연구하는 일이 아닌 만큼, 업무에 당장 활용될 수 있을 만큼의 도전만 가능한 환경이었습니다.
또 팀적으로 이후에는 DevOps의 역할을 더 원했기 때문에, 최근에는 DevOps로서, 팀의 인프라를 총괄하기도 하고 있습니다.
가장 최근에는 게임 서비스를 글로벌로 확장하기위해 하루 수백만의 유저를 수용할 있도록 확장성 있는 클라우드 인프라 구축하는 일을 담당하고 있습니다.

제 첫 직장에서 저는 버블파이터라는 게임을 개발했는데요, 당시 제 관심사를 팀에 잘 어필해서
베이지안 확률 추론을 응용한 TrueSkill 알고리즘을 기반으로 한 매치메이킹 시스템을 디자인하고 구현하는 작업을 도맡아 했습니다.
TrueSkill은 자체적으로도 무척 복잡한 알고리즘인데다, 이것을 이미 서비스 중인 온라인 게임에 녹여내는 것은 무척 도전적인 일이었습니다.
결과적으로는 매치메이킹 시스템을 성공적으로 런칭할 수 있었습니다. 이후 히든 마르코프 연쇄 기법을 이용해서 플레이어들이 얼마나
다음 수초 안에 얼마나 들어올지 예측하고, 이를 통해 매칭 알고리즘을 자동으로 튜닝하도록 하는 시도를 했었는데요,
대학시절 들은 2개의 수업만을 기반으로 했었고, 당시에 학문적 견고함이 부족했던 저로서는 프로토타입에 그쳤습니다.

체계적으로 경험을 쌓지 않고서는, 데이터과학과 인공지능 관련 커리어를 전업으로 담당하기에 쉽지 않을 것이라는 생각이 들었습니다.
다양한 관심사에 흥미가 많던 저는 종종 코세라나 유다시티에서 흥미로운 강좌를 듣곤 하는데요, 최근에는 Coursera의 Deep Learning Specialization을 수강하고 있었습니다.
수강 중에 우연히 다른 재밌는 코스는 없을까? 둘러보다가 MCS-DS 코스를 알게 되었습니다. 이 코스는 완벽히 저를 위한 프로그램이라는 생각이 들었습니다.

저는 현재 제 커리어에 있어서 제네럴리스트입니다. 제가 생각하는 제 강점은 어떤 일에서도 제 자신의 흥미를 찾아낼 수 있고,
이 점이 저를 스스로 빨리 배울 수 있는 사람이게 끔 해왔다는 점입니다. 광범위한 분야의 일들을 성공적으로 수행해왔지만,
정작 데이터과학과 인공지능 관련된 커리어와는 좀 멀어지고 있었던 느낌이랄까요?

MCS-DS 코스를 통해 데이터과학을 체계적으로 배우고, 인공지능을 자유자재로 응용할 수 있는 역량을 키우고 싶습니다.
이후 커리어는 이를 기반으로 데이터과학을 주로 할 수 있도록 이어나갈 수 있을 것으로 기대합니다.
한 편, IT 분야 첨단을 달리는 미국에서 커리어를 이어나가고 싶다는 꿈이 있는데,
MCS-DS는 이 부분에 있어서도 다음 단계로 가는 한 단계 도약일 것으로 기대합니다.

정말 하고 싶었던 데이터과학과 인공지능 관련 경험은 상대적으로 부족해진데다가, 업무적으로 당장 활용 가능한 수준의 업무가 아니고서야
체계적인 기반 하에 데이터과학 경험을 쌓기 힘들다는 생각이 들었습니다.

데이터과학 관련 경험 대부분의 경험이 독학을 통해서 이루어졌기 때문에, Data Science에 있어서 체계적인 학습 경험이 부족하다고 느껴왔습니다.
제다가 후로그람스에서처럼, 계속해서 현재 잘하는 일을 맡게 되다 보면, Data Science로 커리어를 이동해나가는 것이 쉽지 않을 것이라고도 생각해왔구요.
또한, 저는 첨단 기술을 달리는 미국에서 커리어를 이어나가보고 싶다는 꿈도 있습니다.

데이터과학 역량을 체계적으로 기르고, 

철학과에서 절 매료시켰던 것은 물질과 마음의 철학이라는 과목이었습니다.
지능이란 무엇인지, 우리의 뇌와 마음에 대한 과거 철학자들의 통찰을 이해하기도 하고,
관련 주제를 다룬 SF 소설들을 읽고 함께 토론하는 시간도 갖고 했었는데, 이 과목이 무쳑 흥미로웠습니다.

컴퓨터 공학 수업에서 놀랐던 점은 철학과 수업과 컴퓨터 공학이 무척 닮아 있다는 점이었습니다.
철학과에서 재미있게 들었던 기호논리학 수업은 이산수학 수업과 정말 밀접하게 비슷한 내용을 다루고 있었습니다.
컴퓨터 공학 수업에서 제일 좋아했던 AI 수업들은, 물질과 마음의 철학 수업의 심화 과정이라고 느껴질 만큼, 그 학문적 뿌리를 공유하고 있었습니다.

졸업 후 한국에서 제일 유명한 게임 회사 중 하나인 넥슨에 입사했습니다. 저는 버블파이터라는 게임을 개발했는데요,
제 흥미를 잘 어필해서 베이지안 확률 추론을 응용한 TrueSkill 알고리즘을 기반으로 한 매치메이킹 시스템을 디자인하고 구현했습니다.
TrueSkill은 자체적으로도 무척 복잡한 알고리즘인데다, 이것을 서비스 중인 온라인 게임에 녹여내는 것은 무척 도전적인 일이었지만,
매치메이킹 시스템을 성공적으로 런칭할 수 있었습니다.

Data Science와 머신러닝에 더 갈증을 느낀 저는 머신러닝을 기반으로 영화를 추천해주는 Watcha를 서비스하는 Frograms로 직장을 이동했습니다.
당시 저는 머신러닝 외에도 함수형 프로그래밍에 무척 흥미를 갖고 있었는데요,
후로그램스에는 대학원에서 머신러닝을 전공한 데이터 사이언티스트들이 많이 있었고,
덕분에 저는 머신러닝보다는 함수형 언어인 Scala를 활용한 프로그래밍의 전반적인 가이드란일 세우고 코드베이스의 전체적인 품질 향상시키는 일을 맡게 되었습니다.

이후 온라인 오픈월드 게임인 듀랑고를 개발하는 현재 팀인 왓스튜디오에서 일하게 되었습니다.
야생과 오픈월드라는 게임 배경 자체가 흥미로웠고, 데이터 과학을 적용할 여지 역시 더 풍부할 것이라고 기대했습니다.

저는 대부분의 경험이 독학을 통해서 이루어졌기 때문에, Data Science에 있어서 체계적인 학습 경험이 부족하다고 느껴왔습니다.
제다가 후로그람스에서처럼, 계속해서 현재 잘하는 일을 맡게 되다 보면, Data Science로 커리어를 이동해나가는 것이 쉽지 않을 것이라고도 생각해왔구요.
또한, 저는 첨단 기술을 달리는 미국에서 커리어를 이어나가보고 싶다는 꿈도 있습니다.

MCS-DS 코스는 제가 당면한 부족한 접을 잘 채워 줄 수 있으리라는 확신을 얻었습니다.
제 목표를 이루는 도움닫기 과정이 될 것이라 확신합니다.
* Personal Statement Draft4
** 훅(hook) – 시선을 끌기 위한 사적인 이야기. 지원자의 특징이나 경험
Deep Q Learning을 다짜고짜 2주만에 구현해보았던 이야기
Data Science와 AI에 강하게 매료되었다.

** 배경(background) – 지금까지 어떤 성취를 해 왔고 어떤 능력을 갖추고 있는지 서술
- 다양한 분야를 빠르게 배운다.
- TrueSkill 이야기
- 왓챠에서 경험한 Scala와 함수형 언어 경험
- Data Pipeline 구축, DevOps 등

** 프로그램(program) – 이 전공과 분야를 택한 이유에 대한 설명
- 다양한 것을 새롭게 빨리 배우는 장점을 가지고 있지만, 그만큼 스페셜티가 부족하다고 생각한다.
- 그동안의 커리어에서 그걸 말해준다.
- 나의 꿈은 데이터과학과 인공지능을 활용한 게임분야에 더 많이 활용하는 것

** 자기 PR(Self-promotion) – 지원한 프로그램에 자신이 적임자임을 어필
- 대학 때 부터 스스로 공부했던 경험. 게임 디자이너를 위해 철학과를 지원했으나 직접 만들기 위해 프로그래밍을 스스로 공부한 이야기
- 다양한 컴퓨터 서적을 즐겨 읽었으며 코세라나 유다시티 등, 오랫동안 Mooc를 이용했다.
- 기존의 작업들이 모두 Data Science와 어느 정도 연관이 있지만, 튼실한 기반을 갖추고 싶다.

** 앞으로의 계획(Projection) – 어떤 목표를 갖고 있고 앞으로 어떤 일을 하고 싶은지 서술
- IT의 첨단인 미국에서 커리어를 이어나가고 싶다.
- 게임 업계와 데이터 과학 분야를 연결하는 핵심 인재가 되고 싶다.
