#+TITLE: Yeongho Kim
#+EMAIL: yeonghoey@gmail.com

#+OPTIONS: date:nil

#+LATEX_HEADER: \usepackage{enumitem}

#+ATTR_LATEX: :environment itemize :options [label=\null,itemsep=-1ex]
- yeonghoey@gmail.com
- yeonghoey.com
- github.com/yeonghoey

-----

#+BEGIN_QUOTE
Aliquam erat volutpat.  Nunc eleifend leo vitae magna.  In id erat non orci commodo lobortis.  Proin neque massa, cursus ut, gravida ut, lobortis eget, lacus.  Sed diam.  Praesent fermentum tempor tellus.  Nullam tempus.  Mauris ac felis vel velit tristique imperdiet.  Donec at pede.  Etiam vel neque nec dui dignissim bibendum.  Vivamus id enim.  Phasellus neque orci, porta a, aliquet quis, semper a, massa.  Phasellus purus.  Pellentesque tristique imperdiet tortor.  Nam euismod tellus id erat.
#+END_QUOTE


#+BEGIN_EXPORT latex
\newpage
#+END_EXPORT

* Experience
** _[[https://github.com/what-studio][What! Studio]]_
*** Data and DevOps Engineer | June 2016 – Present
In charge of infrastructures for _[[https://durango.nexon.com/en][Durango: Wild Lands]]_, a seamless open world /MMORPG/.

- Built data pipelines for time series data which are generated by distributed game servers. Based on
  /Fluentd/, /Amazon Kinesis Streams/, /AWS Lambda/, /Elasticsearch/, /Spark/ and /Zeppelin/.
- Managed infrastructures (>200 instances) across on /AWS/ (>15 services) via /Terraform/.
- Maintained /Couchbase/, the game's main NoSQL Database, to set up, scale up and out,  monitor / tune performance, etc.
- Evangelized readable, maintainable code styles in /Python/

** _[[http://frograms.com][FROGRAMS]]_
*** Software Engineer  | November 2015 – May 2016
Improved code quality for the recommendation engine of _[[https://watcha.net/][WATCHA]]_ and _[[https://play.watcha.net][WATCHA PLAY]]_,
a Netflix-like movie recommendation and streaming service in Korea.

- Drafted /Scala/ coding standard and made guidelines for the team.
- Introduced /Scala/ code quality tools like /scalafmt/, /scalariform/
- Introduced testing frameworks like /Specs2/, /ScalaCheck/
- Did lots of refactoring on /Scala/ codebase which is based on /Finagle/, high-concurrency RPC framework by /Twitter/.
- Built CI/CD pipeline for the recommendation engine with /Jenkins/, /supervisord/

** [[http://company.nexon.com/Eng/][NEXON Korea]]
*** Game Developer  | December 2013 – November 2015
Broad range of game development for [[http://bf.nexon.com][Bubble Fighter]], A casual TPS Game written in /C++/.

- Designed and implemented Intelligent Matchmaking System based on /TrueSkill/.
  Gave a presentation about it on _[[http://ndcreplay.nexon.com/NDC2015/sessions/NDC2015_0048.html][NEXON Developers Conference 2015]]_ (Korean)
- Wrote anti-hacking codes including memory encryption, hash validation for game data, etc.
- Optimized the games's network performance to cope with severe network conditions when doing localization for Indonesia.
