#+TITLE: Yeongho Kim
#+EMAIL: yeonghoey@gmail.com

#+OPTIONS: date:nil

#+LATEX_HEADER: \usepackage{enumitem}
#+LATEX_HEADER: \usepackage{titling}
#+LATEX_HEADER: \setlength{\droptitle}{-32ex} 

#+BEGIN_EXPORT latex
\vspace{-16ex}
\begin{itemize}[itemindent=20em,align=right,itemsep=-1ex]
  \item[] yeonghoey@gmail.com
  \item[] yeonghoey.com
  \item[] github.com/yeonghoey
\end{itemize}
#+END_EXPORT

#+BEGIN_QUOTE
Aliquam erat volutpat.  Nunc eleifend leo vitae magna.  In id erat non orci commodo lobortis.  Proin neque massa, cursus ut, gravida ut, lobortis eget, lacus.  Sed diam.  Praesent fermentum tempor tellus.  Nullam tempus.  Mauris ac felis vel velit tristique imperdiet.  Donec at pede.  Etiam vel neque nec dui dignissim bibendum.  Vivamus id enim.  Phasellus neque orci, porta a, aliquet quis, semper a, massa.  Phasellus purus.  Pellentesque tristique imperdiet tortor.  Nam euismod tellus id erat.
#+END_QUOTE

* Experience
** [[https://github.com/what-studio][What! Studio]]
*** Data and DevOps Engineer for [[https://durango.nexon.com/en][Durango: Wild Lands]]
: June 2016 – Present

- Built data pipelines for time series data generated by distributed game servers based on
  /Fluentd/, /Amazon Kinesis Streams/, /AWS Lambda/, /Elasticsearch/, /Spark/ and /Zeppelin/.

- Managed infrastructures (>200 instances) across on /AWS/ (>15 services) via /Terraform/.

- Maintained /Couchbase/, the game's main NoSQL Database, to set up, scale up and out,  monitor / tune performance, etc.

- Evangelized readable, maintainable code styles in /Python/

** [[http://frograms.com][FROGRAMS]]
*** Software Engineer for [[https://watcha.net/][WATCHA]] and [[https://play.watcha.net][WATCHA PLAY]]
: November 2015 – May 2016

** [[http://company.nexon.com/Eng/][NEXON Korea]]
*** *Game Developer* for [[http://bf.nexon.com][Bubble Fighter]]
: December 2013 – November 2015

