#+TITLE: Python

* Table of Contents                                                :TOC_2_gh:
 - [[#reference][Reference]]
   - [[#dict][dict]]
   - [[#docstring][docstring]]
   - [[#exceptions][exceptions]]
   - [[#itertools][itertools]]
   - [[#list][list]]
   - [[#multiprocessing][multiprocessing]]
   - [[#re][re]]
   - [[#set][set]]
   - [[#str][str]]
   - [[#string][string]]
   - [[#subprocesses][subprocesses]]
 - [[#details][Details]]
   - [[#comparison][Comparison]]
   - [[#eafp-lbyl][EAFP, LBYL]]
   - [[#final-class][Final class]]
   - [[#source-code-encodings][Source Code Encodings]]
 - [[#staging][Staging]]
   - [[#2017-03-24-fri-python-defining-bound-method][<2017-03-24 Fri> Python, defining bound method]]
   - [[#2017-02-13-mon-isinstance-vs-issubclass][<2017-02-13 Mon> isinstance vs issubclass?]]
   - [[#2017-03-21-tue-generator-and-throw][<2017-03-21 Tue> generator and throw]]
   - [[#2017-05-18-thu-python-int-long-int64][<2017-05-18 Thu> python int, long, int64]]
   - [[#2017-06-09-fri-python-textwrap][<2017-06-09 Fri> python textwrap]]

* Reference
** dict
- https://docs.python.org/2/library/stdtypes.html#mapping-types-dict

#+BEGIN_EXAMPLE
  dict()
  dict(mapping)
  dict(iterable)
  dict(**kwargs)

  len(d)
  d[key]
  d[key] = value
  del d[key]
  key in d
  key not in d
  iter(d)

  D.items()  D.iteritems()  D.viewitems()
  D.keys()   D.iterkeys()   D.viewkeys()
  D.values() D.itervalues() D.viewvalues()

  D.clear()
  D.copy()               a shallow copy of D
  D.fromkeys(S[,v])      new dict with keys from S and values equal to v(None).
  D.get(k[,d])           D[k] if k in D, else d(None)
  D.has_key(k)           True if D has a key k, else False
  D.pop(k[,d]) -> v      remove specified key and return the corresponding value.
                         d(KeyError) if key is not found
  D.popitem() -> (k, v)  remove and return a (key, value) KeyError if empty
  D.setdefault(k[,d])    D.get(k,d), also set D[k]=d if k not in D
  D.update([E, ]**F)
      If E present and has a .keys() method, does:     for k in E: D[k] = E[k]
      If E present and lacks .keys() method, does:     for (k, v) in E: D[k] = v
      In either case, this is followed by: for k in F: D[k] = F[k]
#+END_EXAMPLE

*** items, iteritems, viewitems
- https://stackoverflow.com/questions/10458437/what-is-the-difference-between-dict-items-and-dict-iteritems

**** Py2
- ~items()~: returns a list of tuples(copied elements)
- ~iteritems()~: returns an iterator, can't iterate if ~dict~ changed *after iterator created*
- ~viewitems()~: returns a [[https://docs.python.org/2/library/stdtypes.html#dictionary-view-objects][view object]], can't iterate if ~dict~ changed *during iteration*

#+BEGIN_SRC python
  >>> d = {'a': 0}
  >>> it = d.iteritems()
  >>> d['b'] = 1
  >>> next(it)
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
  RuntimeError: dictionary changed size during iteration
  >>> view = d.viewitems()
  >>> d['c'] = 2
  >>> it = iter(view)
  >>> next(it)
  ('a', 0)
  >>> d['d'] = 3
  >>> next(it)
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
  RuntimeError: dictionary changed size during iteration
#+END_SRC

**** Py3
- ~dict.items()~ == ~dict.viewitems()~ of Py2

** docstring
- https://www.python.org/dev/peps/pep-0257/
- http://epydoc.sourceforge.net/manual-docstring.html
- [[sphinx.org][Sphinx]] reStructuredText based .
- [[docstring-google.py][Google]] and [[docstring-numpy.py][Numpy]] Styles

Specific syntax for variable docstring:
#+BEGIN_SRC python
  #: docstring for x
  x = 22
  x = 22  #: docstring for x
#+END_SRC

** exceptions
- https://docs.python.org/2/library/exceptions.html

If ~str()~ or ~unicode()~ is called on an instance of this class(~BaseException~),
*the representation of the argument(s) to the instance are returned*,
or the empty string when there were no arguments.

~BaseException.args~: The tuple of arguments given to the exception constructor.

#+BEGIN_EXAMPLE
  BaseException
   +-- SystemExit
   +-- KeyboardInterrupt
   +-- GeneratorExit
   +-- Exception
        +-- StopIteration
        +-- StandardError
        |    +-- BufferError
        |    +-- ArithmeticError
        |    |    +-- FloatingPointError
        |    |    +-- OverflowError
        |    |    +-- ZeroDivisionError
        |    +-- AssertionError
        |    +-- AttributeError
        |    +-- EnvironmentError
        |    |    +-- IOError
        |    |    +-- OSError
        |    |         +-- WindowsError (Windows)
        |    |         +-- VMSError (VMS)
        |    +-- EOFError
        |    +-- ImportError
        |    +-- LookupError
        |    |    +-- IndexError
        |    |    +-- KeyError
        |    +-- MemoryError
        |    +-- NameError
        |    |    +-- UnboundLocalError
        |    +-- ReferenceError
        |    +-- RuntimeError
        |    |    +-- NotImplementedError
        |    +-- SyntaxError
        |    |    +-- IndentationError
        |    |         +-- TabError
        |    +-- SystemError
        |    +-- TypeError
        |    +-- ValueError
        |         +-- UnicodeError
        |              +-- UnicodeDecodeError
        |              +-- UnicodeEncodeError
        |              +-- UnicodeTranslateError
        +-- Warning
             +-- DeprecationWarning
             +-- PendingDeprecationWarning
             +-- RuntimeWarning
             +-- SyntaxWarning
             +-- UserWarning
             +-- FutureWarning
       +-- ImportWarning
       +-- UnicodeWarning
       +-- BytesWarning
#+END_EXAMPLE

*** raise MyException vs raise MyException()
- http://stackoverflow.com/questions/16706956/is-there-a-difference-between-raise-exception-and-raise-exception-without
- The short answer is that both ~raise MyException~ and ~raise MyException()~ do the same thing.
- This first form auto instantiates your exception.
- So, use ~raise MyException~ when there are no arguments.

*** SystemExit
- https://docs.python.org/2/library/exceptions.html#exceptions.SystemExit

#+BEGIN_SRC python
  raise SystemExit()       # exit status: 0
  raise SystemExit(99)     # exit status: 99
  raise SystemExit('foo')  # print 'foo', exit status: 1
#+END_SRC

** itertools
- https://docs.python.org/2/library/itertools.html

#+BEGIN_SRC python
  # Generates a break or new group every time the value of the key function changes
  [k for k, g in groupby('AAAABBBCCDAABBB')]   # --> A B C D A B
  [list(g) for k, g in groupby('AAAABBBCCD')]  # --> AAAA BBB CC D
#+END_SRC

** list
- https://docs.python.org/2/library/stdtypes.html#mutable-sequence-types
- https://docs.python.org/2/library/stdtypes.html#sequence-types-str-unicode-list-tuple-bytearray-buffer-xrange

#+BEGIN_EXAMPLE
  x in s
  x not in s
  s + t         the concatenation of s and t
  s * n, n * s  equivalent to adding s to itself n times
  s[i]
  s[i:j]
  s[i:j:k]
  s[i] = x
  s[i:j] = t    slice of s from i to j is replaced by the contents of the iterable t
  del s[i:j]    same as s[i:j] = []
  s[i:j:k] = t  the elements of s[i:j:k] are replaced by those of t
  del s[i:j:k]  removes the elements of s[i:j:k] from the list
  s *= n        updates s with its contents repeated n times
  len(s)
  min(s)
  max(s)

  L.append(object)
  L.count(value) -> integer
  L.extend(iterable)
  L.index(value, [start, [stop]]) -> integer  return first index of value; ValueError on failure
  L.insert(index, object)                     insert object before index
  L.pop([index]) -> item                      remove and return item at index (default last); IndexError on failure
  L.remove(value)                             remove first occurrence of value; ValueError on failure
  L.reverse()                                 reverse *IN PLACE*
  L.sort(cmp=None, key=None, reverse=False)   stable sort *IN PLACE*; cmp(x, y) -> -1, 0, 1
#+END_EXAMPLE

** multiprocessing
- https://docs.python.org/2/library/multiprocessing.html

#+BEGIN_SRC python :results output
  from multiprocessing import Pool
  import time

  def f(id_):
      for _ in range(2):
          print id_
          time.sleep(1)


  # pool must be created AFTER defining functions to apply
  pool = Pool(processes=3)

  for i in range(4):
      pool.apply_async(f, (i,))

  pool.close()  # Prevents any more tasks from being submitted to the pool
  pool.join()
#+END_SRC

#+RESULTS:
: 0
: 1
: 2
: 1
: 0
: 2
: 3
: 3

** re
- https://docs.python.org/2/library/re.html
#+BEGIN_EXAMPLE
  The special characters are:
      "."      Matches any character except a newline.
      "^"      Matches the start of the string.
      "$"      Matches the end of the string or just before the newline at
                the end of the string.
      "*"      Matches 0 or more (greedy) repetitions of the preceding RE.
                Greedy means that it will match as many repetitions as possible.
      "+"      Matches 1 or more (greedy) repetitions of the preceding RE.
      "?"      Matches 0 or 1 (greedy) of the preceding RE.
      ,*?,+?,?? Non-greedy versions of the previous three special characters.
      {m,n}    Matches from m to n repetitions of the preceding RE.
      {m,n}?   Non-greedy version of the above.
      "\\"     Either escapes special characters or signals a special sequence.
      []       Indicates a set of characters.
                A "^" as the first character indicates a complementing set.
      "|"      A|B, creates an RE that will match either A or B.
      (...)    Matches the RE inside the parentheses.
                The contents can be retrieved or matched later in the string.
      (?iLmsux) Set the I, L, M, S, U, or X flag for the RE (see below).
      (?:...)  Non-grouping version of regular parentheses.
      (?P<name>...) The substring matched by the group is accessible by name.
      (?P=name)     Matches the text matched earlier by the group named name.
      (?#...)  A comment; ignored.
      (?=...)  Matches if ... matches next, but doesn't consume the string.
      (?!...)  Matches if ... doesn't match next.
      (?<=...) Matches if preceded by ... (must be fixed length).
      (?<!...) Matches if not preceded by ... (must be fixed length).
      (?(id/name)yes|no) Matches yes pattern if the group with id/name matched,
                          the (optional) no pattern otherwise.

  The special sequences consist of "\\" and a character from the list
  below.  If the ordinary character is not on the list, then the
  resulting RE will match the second character.
      \number  Matches the contents of the group of the same number.
      \A       Matches only at the start of the string.
      \Z       Matches only at the end of the string.
      \b       Matches the empty string, but only at the start or end of a word.
      \B       Matches the empty string, but not at the start or end of a word.
      \d       Matches any decimal digit; equivalent to the set [0-9].
      \D       Matches any non-digit character; equivalent to the set [^0-9].
      \s       Matches any whitespace character; equivalent to [ \t\n\r\f\v].
      \S       Matches any non-whitespace character; equiv. to [^ \t\n\r\f\v].
      \w       Matches any alphanumeric character; equivalent to [a-zA-Z0-9_].
                With LOCALE, it will match the set [0-9_] plus characters defined
                as letters for the current locale.
      \W       Matches the complement of \w.
      \\       Matches a literal backslash.

  This module exports the following functions:
      match    Match a regular expression pattern to the beginning of a string.
      search   Search a string for the presence of a pattern.
      sub      Substitute occurrences of a pattern found in a string.
      subn     Same as sub, but also return the number of substitutions made.
      split    Split a string by the occurrences of a pattern.
      findall  Find all occurrences of a pattern in a string.
      finditer Return an iterator yielding a match object for each match.
      compile  Compile a pattern into a RegexObject.
      purge    Clear the regular expression cache.
      escape   Backslash all non-alphanumerics in a string.

  Some of the functions in this module takes flags as optional parameters:
      I  IGNORECASE  Perform case-insensitive matching.
      L  LOCALE      Make \w, \W, \b, \B, dependent on the current locale.
      M  MULTILINE   "^" matches the beginning of lines (after a newline)
                      as well as the string.
                      "$" matches the end of lines (before a newline) as well
                      as the end of the string.
      S  DOTALL      "." matches any character at all, including the newline.
      X  VERBOSE     Ignore whitespace and comments for nicer looking RE's.
      U  UNICODE     Make \w, \W, \b, \B, dependent on the Unicode locale.
#+END_EXAMPLE

** set
- https://docs.python.org/2/library/stdtypes.html#set-types-set-frozenset

#+BEGIN_EXAMPLE
  x in set
  x not in set
  set.isdisjoint(other)
  set <= other           set.issubset(other)
  set < other            set <= other and set != other
  set >= other           set.issuperset(other)
  set > other            set >= other and set != other
  set | other | ...      set.union(*others)
  set & other & ...      set.intersection(*others)
  set - other - ...      set.difference(*others)
  set ^ other            set.symmetric_difference(other)
                         (either the set or other but not both)
  set.copy()             (a shallow copy of s)

  # only for set, not frozenset
  set |= other | ...     set.update(*others)
  set &= other & ...     set.intersection_update(*others)
  set -= other | ...     set.difference_update(*others)
  set ^= other           set.symmetric_difference_update(other)
  set.add(elem)
  set.remove(elem)       (remove elem. KeyError if elem doesn't exist)
  set.discard(elem)      (remove elem if it is present)
  set.pop()              (remove and return an arbitrary elem. KeyError if empty)
  clear()
#+END_EXAMPLE

#+BEGIN_QUOTE
non-operator versions of union(), intersection(), difference(), and symmetric_difference(), issubset(), and issuperset()
methods *will accept any iterable* as an argument.
In contrast, their *operator based counterparts require their arguments to be sets*.
#+END_QUOTE

#+BEGIN_QUOTE
~set('abc') == frozenset('abc')~ returns ~True~ and so does ~set('abc') in set([frozenset('abc')])~.
#+END_QUOTE

** str
** string
- https://docs.python.org/2/library/stdtypes.html#string-methods

#+BEGIN_EXAMPLE
  S.capitalize() -> string
  S.center(width[, fillchar]) -> string             fillchar=' '
  S.count(sub[, start[, end]]) -> int
  S.decode([encoding[,errors]]) -> object
  S.encode([encoding[,errors]]) -> object
  S.endswith(suffix[, start[, end]]) -> bool        suffix can also be a tuple of strings
  S.expandtabs([tabsize]) -> string                 tabsize=8
  S.find(sub [,start [,end]]) -> int                return -1 on failure
  S.format(*args, **kwargs) -> string
  S.index(sub [,start [,end]]) -> int               raise ValueError on failure
  S.isalnum() -> bool
  S.isalpha() -> bool
  S.isdigit() -> bool
  S.islower() -> bool
  S.isspace() -> bool
  S.istitle() -> bool
  S.isupper() -> bool
  S.join(iterable) -> string
  S.ljust(width[, fillchar]) -> string              fillchar=' '
  S.lower() -> string
  S.lstrip([chars]) -> string or unicode            like S.strip()
  S.partition(sep) -> (head, sep, tail)             If sep is not found, return (S, '', '')
  S.replace(old, new[, count]) -> string
  S.rfind(sub [,start [,end]]) -> int               like S.find()
  S.rindex(sub [,start [,end]]) -> int              like S.index()
  S.rjust(width[, fillchar]) -> string              fillchar=' '
  S.rpartition(sep) -> (head, sep, tail)            like S.partition()
  S.rsplit([sep [,maxsplit]]) -> list of strings    sep=' '
  S.rstrip([chars]) -> string or unicode            like S.strip()
  S.split([sep [,maxsplit]]) -> list of strings     like S.rsplit()
  S.splitlines(keepends=False) -> list of strings
  S.startswith(prefix[, start[, end]]) -> bool      like S.endswith()
  S.strip([chars]) -> string or unicode             remove leading whitespace(or chars)
  S.swapcase() -> string
  S.title() -> string
  S.translate(table [,deletechars]) -> string
  S.upper() -> string                               see also string.maketrans()
  S.zfill(width) -> string                          zero padding for numeric string
#+END_EXAMPLE

*** format
- https://pyformat.info/

** subprocesses
- https://docs.python.org/2/library/subprocess.html

*** Calling an external command in Python
- http://stackoverflow.com/questions/89228/calling-an-external-command-in-python
- https://docs.python.org/2/library/subprocess.html#subprocess.call

#+BEGIN_SRC python
  # Simply exectus shell commands
  os.system("some_command < input_file | another_command > output_file")

  # Deprecated.  Use subprocess
  stream = os.popen("some_command with args")

  # Better, but a little bit complicated
  print subprocess.Popen("echo Hello World",
                         shell=True,
                         stdout=subprocess.PIPE).stdout.read()

  # Same as above, but simply waits until the command completes.
  # Just gives you the return code.
  >>> subprocess.call('exit 1', shell=True)
  1

  # raises an exception on non-zero exit code
  >>> subprocess.check_call('exit 1', shell=True)
  ...
  subprocess.CalledProcessError: Command 'exit 1' returned non-zero exit status 1  output = subpro

  # Gives the output as a string, raises an exception on no-zero exit code
  >>> subprocess.check_output(['echo', 'hi'])
  'hi\n'

#+END_SRC

*** Use PIPE along with communicate()
- http://stackoverflow.com/questions/16768290/understanding-popen-communicate
- Accessing piped streams directly may cause a deadlock because of stream buffering.

#+BEGIN_QUOTE
Warning This will deadlock when using stdout=PIPE and/or stderr=PIPE and
the child process generates enough output to a pipe such that
it blocks waiting for the OS pipe buffer to accept more data. Use communicate() to avoid that.

Use communicate() rather than .stdin.write, .stdout.read or .stderr.read
to avoid deadlocks due to any of the other OS pipe buffersfilling up and blocking the child process.
#+END_QUOTE

*** When to use shell=True
- http://stackoverflow.com/questions/30830642/when-to-use-shell-true-for-python-subprocess-module

- with ~shell=False~, the first argument should be *a list*.
- with ~shell=True~, the first argument should be *a string*.
  - The string for the first argument is like the command you put into the shell prompt.
  - The command can use environment variables, globs, pipes.
  - It's very dangerous, not recommended.

* Details
** Comparison
- https://docs.python.org/2/library/stdtypes.html#comparisons
- http://michael-yxf.appspot.com/?p=251002

#+BEGIN_SRC python
  >>> a = ['0', 9999, {}, [], False, ()]
  >>> a.sort()
  >>> a
  [False, 9999, {}, [], '0', ()]
#+END_SRC

#+BEGIN_QUOTE
CPython implementation detail: Objects of different types except numbers are ordered by their type names;
objects of the same types that don't support proper comparison are ordered by their address.
#+END_QUOTE

** EAFP, LBYL
- https://docs.python.org/3/glossary.html#term-eafp
- https://docs.python.org/3/glossary.html#term-lbyl

#+BEGIN_SRC python
  # EAFP (Easier to ask for forgiveness than permission)
  try:
      return mapping[key]
  except KeyError:
      pass


  # LBYL (Look Before you leap)
  if key in mapping:
      return mapping[key]
#+END_SRC

#+BEGIN_QUOTE
*LBYL* can fail if another thread removes the key after the test, but before the lookup.
This issue can be solved with locks or by using the *EAFP* approach.
#+END_QUOTE

** Final class
- http://stackoverflow.com/questions/2825364/final-classes-in-python-3-x-something-guido-isnt-telling-me

#+BEGIN_SRC python
  class Final(type):
      def __new__(cls, name, bases, classdict):
          for b in bases:
              if isinstance(b, Final):
                  raise TypeError("type '{0}' is not an acceptable base type"
                                  .format(b.__name__))
          return type.__new__(cls, name, bases, classdict)


  class C(object):
      __metaclass__ = Final
#+END_SRC

** Source Code Encodings
- [[https://www.python.org/dev/peps/pep-0263/][PEP 263]]

#+BEGIN_SRC python
  #!/usr/bin/python
  # -*- coding: utf-8 -*-
#+END_SRC
* Staging
** TODO <2017-03-24 Fri> Python, defining bound method
** TODO <2017-02-13 Mon> isinstance vs issubclass?
- https://bugs.python.org/issue25537
** TODO <2017-03-21 Tue> generator and throw
+ http://git.k.nexon.com/k/bronto/merge_requests/222/diffs
** TODO <2017-05-18 Thu> python int, long, int64
** TODO <2017-06-09 Fri> python textwrap
