#+TITLE: TOEFL Speaking

* Table of Contents :TOC_3_gh:
- [[#independent][Independent]]
  - [[#questions-1][Questions 1]]
    - [[#animals][Animals]]
    - [[#book][Book]]
    - [[#country][Country]]
    - [[#education][Education]]
    - [[#experience][Experience]]
    - [[#family][Family]]
    - [[#friend][Friend]]
    - [[#person][Person]]
    - [[#place][Place]]
    - [[#preferences][Preferences]]
    - [[#sports][Sports]]
    - [[#characteristics][Characteristics]]
    - [[#uncategorized][Uncategorized]]
  - [[#questions-2][Questions 2]]

* Independent
** Questions 1
*** Animals
- Describe your experience with animals and how you feel about pets.
- Describe your experiences with animals and how you fell about pets.

*** Book
- Describe the book that you found most interesting.
- What is the book you want to read again?
- Describe the book that you read and became most impressively.

*** Country
- Describe the country you would most like to visit and explain why.
- What is the most important holiday in your country?
- Choose a place in your country that you would recommend that a foreign friend visit.
- Describe a social or political event in your country.
- Describe about the transportation in your country.
- Describe a holiday in your country.
- What’s your favorite holiday?

*** Education
- Describe the memorable class in your life.
- Describe the memorable event from the school you had attended.
- What could be the most important quality of a good teacher?

*** Experience
- What is an event you remember well, such as an anniversary or birthday?
- What do you consider your most important achievement?
- What is the most meaningful gift you have ever received?
- What was difficult experience you went through?
- Which one has caused you the most regret?
- What is the worst vacation you have ever had?
- Describe a difficult problem in your life that required a clever solution.
- Explain a time in your life when you had a difficult time sharing a room or apartment with other people.
- Which was the most important decision in your life?
- What was the most important decision in your life?
- What was a difficult experience you went through?
- Describe a difficult problem in your life that required a clever solution.
- What was your most valuable experience in you life?
- What was the most important reason that you made?
- Explain a time in your life when you had a difficult time sharing a room or apartment with other people.

*** Family
- Describe a time in your life when you have benefit from contact with an extended family member.
- What is a useful skill your mother or father taught you?
- Describe a time in your life when you felt proud of a member of your family.
- Describe a time in your life when you have benefited from contact with an extended family member.

*** Friend
- Describe an important friend in your life.
- Explain a time in your life when a friend of yours had a negative influence on you.
- What could be the important characteristic of good friend?
- plain a time in your life when a friend of your had a negative influence on you.

*** Person
- Describe an influential role model in your life.
- Describe one historical figure you would like to meet and explain why.
- Describe the memorable person in your life.
- Explain about the most influencing person in your group or community.
- Describe the person you admire most.
- Which person has helped you the most to get where you are today.
- What person who is alive today would you most like to meet? 
- Who is the most memorable teacher?
- The last time you needed to discuss something important, who did you talk with?

*** Place
- Choose the most important room in your house and explain why it’s important to you.
- Describe the most memorable place you have ever visited
- Which is the best city you have visited?
- Which is the best city you would live to live?
- Describe the city that you want to visit
- Describe the city attractions you live in.
- Which is the best public place you would like to go?
- Where do you go to meet your friends?
- Which park do you go often?
- If you could live anywhere, where would you live?
- If you could live abroad, where would you go?

*** Preferences
- Describe your favorite method of staying health.
- What is your favorite movie genre?
- Describe your favorite food from your native country.
- What is your favorite season and why?
- What is your favorite pastime?
- How did you spend your free time in high school?
- What kind of work are you willing to do even if you never get paid for it?
- What is the best way to reduce stress?
- Which could be the best invention of the mankind? Why?
- Do you consider childtime important?
- What do you consider when you go to restaurants or food stands?
- How did you spend your free time in high school?
- What does your dream house look like?
- What is your favorite food?
- Why are you preparing to take the TOEFL test?
- What was your favorite subject when you were in high school?

*** Sports
- Which is the most favored sports in your country? 

*** Characteristics
- What do you think of characteristics of good parents?
- What do you think of characteristics of good students?
- What do you think of characteristics of good teachers?
- What do you think of characteristics of good sons and daughter?

*** Uncategorized
- If you suddenly got $10 million, what would you spend it on? 
- What changes would you make in next 10 years?
** Questions 2
- Some people believe the advent of computers has made human lives better. Others say computers have a negative effect on society. Explain with which side you agree and why.
- Some college students live in dormitories. Others live off campus. Which place do you think is better for students to live and why? 
- Some people spend their lives in one location, and others choose to move around from one place to another. Which do you think is better and why?
- Some students prefer to learn on their own. Others seek help from a teacher. Which method do you think is better for students and why?
- Some people like to attend live performance while others prefer watching them on television. Which do you prefer and why?
- Some students like to study in large classes while others like to study in small ones. Which method do you think is more effective for students and why?
- Some students prefer to attend universities in big cities, while others choose small towns for their higher education. Which do you prefer and why?
- Some people make decision instantly. Others only decide after thinking about their choice for a long time. Which approach do you think is better and why?
- Some people try to perform several tasks at once while others prefer to concentrate on one specific task at a time. Which approach do you think is more effective and why?
- Some schools offer field trips to zoos and other schools offer field trips to natural history museums. Which do you think is better for students and why?
- Some companies require their employees to wear formal business attire. Others allow casual dress. Which do you prefer and why?
- Some people like to eat out while others like to cook at home. Which do you think is better and why? 
- Some people enjoy traveling around their own countries while others prefer traveling abroad. Which do you prefer and why?
- Some people like to communicate face-to-face while others like to communicate through e-mail. Which method do you prefer and why?
- Some university students are supposed financially by their parents, while others support themselves with part-time jobs. Which do you think is more beneficial for students and why?
- Some people prefer to take public transportation to work or school. Others like to drive their own cars. Which do you prefer? Include details and examples in your explanation. 
- Describe a person that you admire. Explain why you admire this person.
- Would you like to try a dangerous or extreme sport? If yes, which one, If no, why not?
- Some movies are made just to entertain audiences, while others are meant to make audiences think about certain issues. Which type of movie do you prefer? Describe a movie you saw that represents your preferred type of movie.
- Sometimes students have to write papers. Sometimes they have to give oral presentations. Which activity do you think is more helpful for students? Why? Include details and examples in your explanation.
- The local government wishes to improve the quality of transportation. Do you think they should increase the number of buses in your town or build a subway? Give reasons and details for your answer.
- People all over the world spend time watching television. In some countries, watching television has replaced more active pastime such as sports or visiting with friends. Describe whether television watching has had a good or bad effect on society. Provide clear examples to support your opinion.
- If you won some money, which would you prefer to buy, an SUV or a sports car? Give details and reasons supporting your answer.
- Some people like to enjoy their money as they earn it. Others like to save their money to use sometimes in the future. Which do you prefer?
- Some married couples choose to have large families, while others choose not to have any children. Which type of family do you want? Include details and examples in your explanation.
- Some people choose to spend their vacation at luxury resorts, while others prefer to backpack through different areas. Which kind of vacation do you prefer? Include details and examples in your explanation.
- Governments always have to choose how to spend tax money to keep the country working properly. Do you think it is better for your country’s government to spend more money on the military or on post-secondary (university or college) education? Include details and examples in your explanation.
- There is a saying ”charity starts at home.” This means that it is better to help charities in your own neighborhood country rather than charities in other places. Do you agree or disagree with this opinion? Include details and examples in your explanation.
- Some people feel that dance plays an important role in a culture in a culture. Do you agree or disagree? Support your answer with specific reasons and examples.
- Would you prefer to live in a traditional house or in a modern apartment building? Use specific reasons and details to support your choice.
- You have enough money to purchase either a house or a business. Which would you choose to buy? Give specific reasons to explain your choice.
- Many students choose to attend schools or universities outside their home countries. Why do some students study abroad? Use specific reasons and details to explain your answer.
- Some people prefer to live in a small town. Others prefer to live in a big city. Which place would you prefer to live in? Use specific reasons and details to support your answer.
- Some people prefer to eat at food stands or restaurants. Other people prefer to prepare and eat food at home. Which do you prefer? Use specific reasons and examples to support your answer.
- Some people prefer to get up early in the morning and start the day's work. Others prefer to get up later in the day and work until late at night. Which do you prefer? Use specific reasons and examples to support your choice.
- If you could buy either a sports car or a sedan, what would you buy and why?
- Do you prefer to play sports or watch sports? Use reasons to support your response.
- Some people prefer to spend their free time outdoors. Other people prefer to spend their leisure time indoors. Would you prefer to be outside or would you prefer to be inside for your leisure activities?
- Today, there are many people shopping online. Do you prefer shopping online rather than going shopping to the mall or market? 
- Some students prefer to study alone. Others prefer to study with a group of students. Which do you prefer? Use specific reasons and examples to support your answer.  
- You have received a gift of money. The money is enough to buy either a piece of jewelry you like or tickets to a concert you want to attend. Which would you buy? Use specific reasons and details to support your answer.
- Some people prefer to work for a large company. Others prefer to work for a small company. Which would you prefer? Use specific reasons and details to support your choice.
- Some people prefer to work for themselves or own a business. Others prefer to work for an employer. Would you rather be self-employed, work for someone else, or own a business? Use specific reasons to explain your choice.
- Discuss whether television watching has had a good or bad effect on society. Provide clear examples to support your opinion.
- Your school has enough money to purchase either computers for students or books for the library. Which should your school choose to buy – computers or books?
- Do you agree or disagree with the following statement? Reading fiction (such as novels and short stories) is more enjoyable than watching movies.
- Some people prefer to spend most of their free time alone while others like to be with friends or families. Do you prefer to spend your free time alone or with others?
- If you could study a subject, which one would you study – Math or English? Explain your choice, using specific reasons and details.
- If you could go to either a place in the future or a place in the past. Which one would you choose? Include your reasons and details.
- Which do you think it’s more important to be successful in this society among physical appearance or characteristics? Explain your response with reasons and examples.
- If you won a prize, which would you choose – entrance ticket to an amusement park or to a concert? Include reasons and examples to support your answer.
- Do you prefer to live with your extended family or with your nuclear family? Give details and reasons to support your answer.
- Which do you think is better – to live in a dormitory or to rent an apartment near your campus?
- Some people prefer going to a movie theater instead of renting videos or DVDs. Which one do you prefer – going to a movie theater or renting videos or DVDs?
- Some people prefer learning from books and others prefer learning from personal experience. Which one do you prefer?
- Do you want to live with roommate or live alone?
- Do you agree with the idea that computers make people comfortable?
- Do you think that physical classes are necessaries to high school students?
- Do you think that music and art classes are necessaries to high school students?
- Do you think it is possible for everybody can attend universities?
- Which have more effects on you between radio and your neighbors?
- Which do you think that governments invest between museums and art galleries?
